### ISSUE TITLE
Lots of inserted blank lines

### ISSUE THREAD

**Issue by brandonkal** [jaredpetersen/codeprinter#35] opened 2019-11-27 17:58 UTC
The code printer inserts many blank lines (~6 pages) at around line 415.

https://raw.githubusercontent.com/openfaas-incubator/ofc-bootstrap/master/main.go

**Comment by jaredpetersen** [comment] 2019-12-03 07:12
Hey -- thanks for submitting an issue.

That's super interesting and not something I've seen before. I've noticed that if you don't hit the line number button the blank pages don't appear. Here are some screenshots to document the behavior:

**No Line Numbers**
![Screen Shot 2019-12-02 at 10 56 45 PM](https://user-images.githubusercontent.com/8802128/70027489-1eb8ff80-1557-11ea-9d48-23d3dafc16c1.png)

**Line Numbers**
![Screen Shot 2019-12-02 at 10 57 02 PM](https://user-images.githubusercontent.com/8802128/70027498-24164a00-1557-11ea-9ff4-55fe870d66b3.png)

![Screen Shot 2019-12-02 at 10 57 11 PM](https://user-images.githubusercontent.com/8802128/70027505-2678a400-1557-11ea-85e5-b2f96a716e81.png)

I believe the problem is because it's a particularly long piece of code and/or the code has lots of long lines that have to be wrapped to fit the page.

Here's another piece of pretty terrible code that I wrote a while back that exhibits the same issue on line 427 (according to codeprinter's line count):

https://raw.githubusercontent.com/jaredpetersen/osfinder/master/OSFinder.java

If I remember correctly, line numbers are generated by a library and kind of hacked in to the print layout with some CSS stuff. It's definitely possible there are gremlins hiding in there.

**Comment by jaredpetersen** [comment] 2019-12-03 07:19
Apparently there's not any CSS shenanigans on codeprinter's part. Looks like I just use a library now now (I'm not cool enough to write my own):

https://github.com/jaredpetersen/codeprinter/blob/master/src/editor/document/index.jsx#L79-L89

Wondering if the `react-syntax-highlighter` library has a fix for this.

**Comment by jaredpetersen** [comment] 2019-12-03 07:26
There's been a major release of that library since it was last included in this project so that would definitely be the next place to look whenever someone (or myself) has time. At the very least, upgrading it would be a good idea regardless of whether or not it solves this problem.

**Comment by jaredpetersen** [comment] 2019-12-15 03:44
Upgraded the library locally without any luck.

The problem is that the lines of code being printed are too long for the page so the web browser wraps them. The library just adds line numbers for each real line of code and [doesn't support line wrapping](https://github.com/conorhastings/react-syntax-highlighter/issues/143), so you end up with a bunch of missing line numbers at the end.

Going to look at some way of fixing this.

**Closed** 2019-12-21 08:32 UTC
Labels: bug

**Comment by jaredpetersen** [comment] 2019-12-21 08:43
@brandonkal This has been fixed!
