### ISSUE TITLE
Too small font on some pages

### ISSUE THREAD

**Issue by haideralipunjabi** [jaredpetersen/codeprinter#23] opened 2017-08-29 15:59 UTC
I used your tool to generate around 30+ PDFs, and 4 of them got weirdly small font. Here is one of them.
[KVS_BusRoutes.html.pdf](https://github.com/jaredpetersen/codeprinter/files/1260906/KVS_BusRoutes.html.pdf)

I couldn't understand why this is happening. I am 80% sure it is due to something in the code (all 4 codes have too similar code), but couldn't figure out what.

**Comment by jaredpetersen** [comment] 2017-08-30 00:15
@haideralipunjabi - Can you post a copy of one of the code files that resulted in weirdly small font along with the exact Codeprinter settings (font face, font size, and highlighting style) that you used? I tried just pasting the text from that PDF but couldn't reproduce the issue.

**Comment by haideralipunjabi** [comment] 2017-09-01 10:22
[This is the code that I am using](https://github.com/codeclubtbms/TBMS-Website/blob/master/KVS/BusRoutes.html).
The settings are:
Font - Courier
Font Size: 12px
Highlighter: Github

**Comment by jaredpetersen** [comment] 2017-09-02 06:19
@haideralipunjabi I'm not able to reproduce the issue:

PDF:
[haider.pdf](https://github.com/jaredpetersen/codeprinter/files/1271948/haider.pdf)

Screenshot:
<img width="1792" alt="screen shot 2017-09-01 at 11 12 56 pm" src="https://user-images.githubusercontent.com/8802128/29993424-8a9c806a-8f6b-11e7-8581-3f67d99f9386.png">

Have you tried using a different browser?

**Comment by haideralipunjabi** [comment] 2017-09-02 07:55
@jaredpetersen I tried it with Chrome and it worked :)

The issue was on Firefox 55.0.2 (64-bit) Ubuntu, if it is of any help

**Comment by jaredpetersen** [comment] 2017-09-02 21:52
Ah! I was able to reproduce the issue in Firefox 54.0.1 (64-bit) Mac (looks like I need an update).

The problem is your Firefox settings. If you leave the "Ignore Scaling and Shrink to Page Width" option checked in the details menu of print dialog, it will shrink your code since you have some really long lines in there. Firefox should be fine, just make sure to uncheck that box.

<img width="606" alt="screen shot 2017-09-02 at 2 49 54 pm" src="https://user-images.githubusercontent.com/8802128/29999022-43a94606-8fee-11e7-980a-67530fca446f.png">

**Closed** 2017-09-02 21:53 UTC

**Comment by haideralipunjabi** [comment] 2017-09-03 14:02
:rofl: Never knew about that
Thanks
